// Generated by js_of_ocaml 2.6
(function(bK){"use strict";var
by=254,aB=".",aa=255,bn="x",bo="Sys_error",aG="i",aA="+",$=65535,bx="Invalid_argument",bw='"',G=16777215,bg=250,ai=1024,bm="%u",bl="%d",bk=110,bv="o",a$=127,bj="'",bu="End_of_file",bt=120,M=" ",bf=-10,aE="e",bs="Failure",a_="Undefined_recursive_module",aD="d",be="% ",bi="X",S="-",a9="nan",bd="Stack_overflow",n="",T=128,bc=100,aC=" : file already exists",F="0",a8="%+",b=248,bb="Not_found",aF="%#",R="%",a6="Assert_failure",a7="/",bq="Sys_blocked_io",br="fd ",az="%i",bh="Out_of_memory",ba="Match_failure",a="camlinternalFormat.ml",bp="Division_by_zero";function
aM(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
aL(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
e=n;for(;0<c;b+=ai,c-=ai)e+=d.apply(null,aM(a,b,Math.min(c,ai)));return e}function
aj(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
D(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?aL(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?aL(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)aj(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
dW(a,b){var
e=a.length,d=new
Array(e+1),c=0;for(;c<e;c++)d[c]=a[c];d[c]=b;return d}function
ab(c,b){if(c.fun)return ab(c.fun,b);var
a=c.length,d=b.length,e=a-d;if(e==0)return c.apply(null,b);else
if(e<0)return ab(c.apply(null,aM(b,0,a)),aM(b,a,d-a));else
return function(a){return ab(c,dW(b,a))}}function
dp(a){if(isFinite(a)){if(Math.abs(a)>=2.22507385850720138e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
aq(a,b){if(b.repeat)return b.repeat(a);var
c=n,d=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;d++;if(d==9)b.slice(0,1)}}function
ak(a){if(a.t==2)a.c+=aq(a.l-a.c.length,"\0");else
a.c=aL(a.c,0,a.c.length);a.t=0}function
dG(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>a$)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
dT(a){for(var
j=n,d=n,g,f,h,b,c=0,i=a.length;c<i;c++){f=a.charCodeAt(c);if(f<T){for(var
e=c+1;e<i&&(f=a.charCodeAt(e))<T;e++);if(e-c>512){d.substr(0,1);j+=d;d=n;j+=a.slice(c,e)}else
d+=a.slice(c,e);if(e==i)break;c=e}b=1;if(++c<i&&((h=a.charCodeAt(c))&-64)==T){g=h+(f<<6);if(f<224){b=g-12416;if(b<T)b=1}else{b=2;if(++c<i&&((h=a.charCodeAt(c))&-64)==T){g=h+(g<<6);if(f<240){b=g-925824;if(b<2048||b>=55295&&b<57344)b=2}else{b=3;if(++c<i&&((h=a.charCodeAt(c))&-64)==T&&f<245){b=h-63447168+(g<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else
if(b>$)d+=String.fromCharCode(55232+(b>>10),56320+(b&1023));else
d+=String.fromCharCode(b);if(d.length>ai){d.substr(0,1);j+=d;d=n}}return j+d}function
dS(a){switch(a.t){case
9:return a.c;default:ak(a);case
0:if(dG(a.c)){a.t=9;return a.c}a.t=8;case
8:return dT(a.c)}}function
H(a,b,c){this.t=a;this.c=b;this.l=c}H.prototype.toString=function(){return dS(this)};function
dL(a,b){throw[0,a,b]}function
d(a){return new
H(0,a,a.length)}function
bH(a,b){dL(a,d(b))}var
z=[0];function
ac(a){bH(z.Invalid_argument,a)}function
v(a){if(a<0)ac("String.create");return new
H(a?2:9,n,a)}function
dr(a,b,c,d){if(c>0)if(b==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(d==0){a.c=n;a.t=2}else{a.c=aq(c,String.fromCharCode(d));a.t=c==a.l?0:2}else{if(a.t!=4)aj(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
bz(a){if((a.t&6)!=0)ak(a);return a.c}function
aJ(a){a=bz(a);var
e=a.length;if(e>31)ac("format_int: format too long");var
b={justify:aA,signstyle:S,filler:M,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=S;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=F;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;case"d":case"i":b.signedconv=true;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
aH(a,b){if(a.uppercase)b=b.toUpperCase();var
f=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!=S))f++;if(a.alternate){if(a.base==8)f+=1;if(a.base==16)f+=2}var
c=n;if(a.justify==aA&&a.filler==M)for(var
e=f;e<a.width;e++)c+=M;if(a.signedconv)if(a.sign<0)c+=S;else
if(a.signstyle!=S)c+=a.signstyle;if(a.alternate&&a.base==8)c+=F;if(a.alternate&&a.base==16)c+="0x";if(a.justify==aA&&a.filler==F)for(var
e=f;e<a.width;e++)c+=F;c+=b;if(a.justify==S)for(var
e=f;e<a.width;e++)c+=M;return d(c)}function
ds(a,b){var
c,f=aJ(a),e=f.prec<0?6:f.prec;if(b<0){f.sign=-1;b=-b}if(isNaN(b)){c=a9;f.filler=M}else
if(!isFinite(b)){c="inf";f.filler=M}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)==aE)c=c.slice(0,d-1)+F+c.slice(d-1);break;case"f":c=b.toFixed(e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(aE),h=+c.slice(i+1);if(h<-4||b>=1e+21||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)==F)d--;if(c.charAt(d)==aB)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)==aE)c=c.slice(0,d-1)+F+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)==F)d--;if(c.charAt(d)==aB)d--;c=c.slice(0,d+1)}}break}return aH(f,c)}function
al(a,b){if(bz(a)==bl)return d(n+b);var
c=aJ(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
e=b.toString(c.base);if(c.prec>=0){c.filler=M;var
f=c.prec-e.length;if(f>0)e=aq(f,F)+e}return aH(c,e)}function
dv(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
dF(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
dN(a,b){a.t&6&&ak(a);b.t&6&&ak(b);return a.c<b.c?-1:a.c>b.c?1:0}function
bA(a,b,c){var
e=[];for(;;){if(!(c&&a===b))if(a
instanceof
H)if(b
instanceof
H){if(a!==b){var
d=dN(a,b);if(d!=0)return d}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
f=a[0];if(f===by)f=0;if(f===bg){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
g=b[0];if(g===by)g=0;if(g===bg){b=b[1];continue}else
if(f!=g)return f<g?-1:1;else
switch(f){case
248:var
d=dF(a[2],b[2]);if(d!=0)return d;break;case
251:ac("equal: abstract value");case
255:var
d=dv(a,b);if(d!=0)return d;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)e.push(a,b,1)}}else
return 1}else
if(b
instanceof
H||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!="number"&&a&&a.compare)return a.compare(b,c);else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!c)return NaN;if(a==a)return 1;if(b==b)return-1}}if(e.length==0)return 0;var
h=e.pop();b=e.pop();a=e.pop();if(h+1<a.length)e.push(a,b,h+1);a=a[h];b=b[h]}}function
du(a,b){return+(bA(a,b,false)>=0)}function
dy(a){return(a[3]|a[2]|a[1])==0}function
dB(a){return[aa,a&G,a>>24&G,a>>31&$]}function
bF(a){var
d=a.length,c=new
Array(d);for(var
b=0;b<d;b++)c[b]=a[b];return c}function
dC(a,b){var
c=a[1]-b[1],d=a[2]-b[2]+(c>>24),e=a[3]-b[3]+(d>>24);return[aa,c&G,d&G,e&$]}function
bC(a,b){if(a[3]>b[3])return 1;if(a[3]<b[3])return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
bB(a){a[3]=a[3]<<1|a[2]>>23;a[2]=(a[2]<<1|a[1]>>23)&G;a[1]=a[1]<<1&G}function
dz(a){a[1]=(a[1]>>>1|a[2]<<23)&G;a[2]=(a[2]>>>1|a[3]<<23)&G;a[3]=a[3]>>>1}function
dE(a,b){var
e=0,d=bF(a),c=bF(b),f=[aa,0,0,0];while(bC(d,c)>0){e++;bB(c)}while(e>=0){e--;bB(f);if(bC(d,c)>=0){f[1]++;d=dC(d,c)}dz(c)}return[0,f,d]}function
dD(a){return a[1]|a[2]<<24}function
dx(a){return a[3]<<16<0}function
dA(a){var
b=-a[1],c=-a[2]+(b>>24),d=-a[3]+(c>>24);return[aa,b&G,c&G,d&$]}function
dw(a,b){var
c=aJ(a);if(c.signedconv&&dx(b)){c.sign=-1;b=dA(b)}var
d=n,h=dB(c.base),g="0123456789abcdef";do{var
f=dE(b,h);b=f[1];d=g.charAt(dD(f[2]))+d}while(!dy(b));if(c.prec>=0){c.filler=M;var
e=c.prec-d.length;if(e>0)d=aq(e,F)+d}return aH(c,d)}function
am(a){return+(a>31&&a<a$)}function
I(a){bH(z.Sys_error,a)}function
dH(a){if(!a.opened)I("Cannot flush a closed channel");if(a.buffer==n)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=n;return 0}var
bJ=0;function
dX(){return new
Date().getTime()/1e3}function
aN(){return Math.floor(dX())}function
N(a){this.data=a;this.inode=bJ++;var
b=aN();this.atime=b;this.mtime=b;this.ctime=b}N.prototype={truncate:function(){this.data=v(0);this.modified()},modified:function(){var
a=aN();this.atime=a;this.mtime=a}};function
g(a){return a.l}function
bG(a){a=a
instanceof
H?a.toString():a;I(a+": No such file or directory")}var
dq=a7;function
an(a){a=a
instanceof
H?a.toString():a;if(a.charCodeAt(0)!=47)a=dq+a;var
d=a.split(a7),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(n);break;default:b.push(d[c]);break}b.orig=a;return b}function
P(){this.content={};this.inode=bJ++;var
a=aN();this.atime=a;this.mtime=a;this.ctime=a}P.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
ap=new
P();ap.mk(n,new
P());function
aI(a){var
b=ap;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))bG(a.orig);b=b.get(a[c])}return b}function
dR(a){var
c=an(a),b=aI(c);return b
instanceof
P?1:0}function
dO(a){return new
H(4,a,a.length)}function
d2(a){if(a.t!=4)aj(a);return a.c}function
dt(a,b){var
f=an(a),c=ap;for(var
g=0;g<f.length-1;g++){var
e=f[g];if(!c.exists(e))c.mk(e,new
P());c=c.get(e);if(!(c
instanceof
P))I(f.orig+aC)}var
e=f[f.length-1];if(c.exists(e))I(f.orig+aC);if(b
instanceof
P)c.mk(e,b);else
if(b
instanceof
N)c.mk(e,b);else
if(b
instanceof
H)c.mk(e,new
N(b));else
if(b
instanceof
Array)c.mk(e,new
N(dO(b)));else
if(b.toString)c.mk(e,new
N(d(b.toString())));else
ac("caml_fs_register");return 0}function
dQ(a){var
b=ap,d=an(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
af(a,b,c){if(z.fds===undefined)z.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?g(b.data):0;d.flags=c;z.fds[a]=d;z.fd_last_idx=a;return a}function
d3(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
f=a.toString(),h=an(a);if(d.rdonly&&d.wronly)I(f+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)I(f+" : flags Open_text and Open_binary are not compatible");if(dQ(a)){if(dR(a))I(f+" : is a directory");if(d.create&&d.excl)I(f+aC);var
g=z.fd_last_idx?z.fd_last_idx:0,e=aI(h);if(d.truncate)e.truncate();return af(g+1,e,d)}else
if(d.create){var
g=z.fd_last_idx?z.fd_last_idx:0;dt(a,v(0));var
e=aI(h);return af(g+1,e,d)}else
bG(a)}af(0,new
N(v(0)));af(1,new
N(v(0)));af(2,new
N(v(0)));function
dI(a){var
b=z.fds[a];if(b.flags.wronly)I(br+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
dU(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=bK.console;b&&b.error&&b.error(a)}function
dV(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=bK.console;b&&b.log&&b.log(a)}var
ao=new
Array();function
dM(a,b){var
i=d(b),c=g(i),h=g(a.file.data),f=a.offset;if(f+c>=h){var
e=v(f+c);D(a.file.data,0,e,0,h);D(i,0,e,f,c);a.file.data=e}a.offset+=c;a.file.modified();return 0}function
bD(a){var
b;switch(a){case
1:b=dV;break;case
2:b=dU;break;default:b=dM}var
d=z.fds[a];if(d.flags.rdonly)I(br+a+" is readonly");var
c={file:d.file,offset:d.offset,fd:a,opened:true,buffer:n,output:b};ao[c.fd]=c;return c}function
dJ(){var
a=0;for(var
b
in
ao)if(ao[b].opened)a=[0,ao[b],a];return a}if(!Math.imul)Math.imul=function(a,b){b|=0;return((a>>16)*b<<16)+(a&$)*b|0};var
bE=Math.imul;function
ad(a,b){return+(bA(a,b,false)!=0)}function
c(a,b,c){z[a+1]=b;if(c)z[c]=b}var
dK=0;function
aK(a){a[2]=dK++;return a}function
bI(){ac("index out of bounds")}function
ar(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
B(a,b){if(b>>>0>=a.l)bI();return ar(a,b)}function
r(a,b,c){c&=aa;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}aj(a)}a.c[b]=c;return 0}function
ae(a,b,c){if(b>>>0>=a.l)bI();return r(a,b,c)}function
dP(){return 32}function
O(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
k(a,b){return{joo_tramp:a,joo_args:b}}function
j(a,b){return a.length==1?a(b):ab(a,[b])}function
C(a,b,c){return a.length==2?a(b,c):ab(a,[b,c])}var
aP=[b,d(bs),-3],aO=[b,d(bx),-4],s=[b,d(a6),-11];c(11,[b,d(a_),-12],a_);c(10,s,a6);c(9,[b,d(bq),bf],bq);c(8,[b,d(bd),-9],bd);c(7,[b,d(ba),-8],ba);c(6,[b,d(bb),-7],bb);c(5,[b,d(bp),-6],bp);c(4,[b,d(bu),-5],bu);c(3,aO,bx);c(2,aP,bs);c(1,[b,d(bo),-2],bo);c(0,[b,d(bh),-1],bh);var
bM=d("true"),bN=d("false"),bL=d("Pervasives.Exit"),bR=d("\\b"),bS=d("\\t"),bT=d("\\n"),bU=d("\\r"),bQ=d("\\\\"),bP=d("\\'"),bX=d("String.blit / Bytes.blit_string"),bW=d("Bytes.blit"),bV=d("String.sub / Bytes.sub"),bY=d(n),bZ=d("Sys.Break"),b0=d("Buffer.add: cannot grow buffer"),b9=d("%c"),b_=d("%s"),b$=d(az),ca=d("%li"),cb=d("%ni"),cc=d("%Li"),cd=d("%f"),ce=d("%B"),cf=d("%{"),cg=d("%}"),ch=d("%("),ci=d("%)"),cj=d("%a"),ck=d("%t"),cl=d("%?"),cm=d("%r"),cn=d("%_r"),co=[0,d(a),816,23],cz=[0,d(a),780,21],cr=[0,d(a),781,21],cA=[0,d(a),784,21],cs=[0,d(a),785,21],cB=[0,d(a),788,19],ct=[0,d(a),789,19],cC=[0,d(a),792,22],cu=[0,d(a),793,22],cD=[0,d(a),797,30],cv=[0,d(a),798,30],cx=[0,d(a),802,26],cp=[0,d(a),803,26],cy=[0,d(a),812,28],cq=[0,d(a),813,28],cw=[0,d(a),817,23],dd=d(bm),db=[0,d(a),1449,4],dc=d("Printf: bad conversion %["),de=[0,d(a),1517,39],df=[0,d(a),1540,31],dg=[0,d(a),1541,31],a5=d("Printf: bad conversion %_"),dh=d("@{"),di=d("@["),c$=[0,d(bj),[0,d(bj),0]],c9=d(a9),c_=d(aB),c7=d("neg_infinity"),c8=d("infinity"),c6=d("%.12g"),cT=[0,d(R),[0,d(aD),0]],cU=[0,d(a8),[0,d(aD),0]],cV=[0,d(be),[0,d(aD),0]],cW=[0,d(R),[0,d(aG),0]],cX=[0,d(a8),[0,d(aG),0]],cY=[0,d(be),[0,d(aG),0]],cZ=[0,d(R),[0,d(bn),0]],c0=[0,d(aF),[0,d(bn),0]],c1=[0,d(R),[0,d(bi),0]],c2=[0,d(aF),[0,d(bi),0]],c3=[0,d(R),[0,d(bv),0]],c4=[0,d(aF),[0,d(bv),0]],c5=[0,d(R),[0,d("u"),0]],cG=d(bl),cH=d("%+d"),cI=d("% d"),cJ=d(az),cK=d("%+i"),cL=d("% i"),cM=d("%x"),cN=d("%#x"),cO=d("%X"),cP=d("%#X"),cQ=d("%o"),cR=d("%#o"),cS=d(bm),cF=[0,d(bw),[0,d(bw),0]],b1=d("@]"),b2=d("@}"),b3=d("@?"),b4=d("@\n"),b5=d("@."),b6=d("@@"),b7=d("@%"),b8=d("@"),cE=d("CamlinternalFormat.Type_mismatch"),dm=[0,[4,3,0,0,0],d(az)];function
q(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,q(a[1])];case
1:return[1,q(a[1])];case
2:return[2,q(a[1])];case
3:return[3,q(a[1])];case
4:return[4,q(a[1])];case
5:return[5,q(a[1])];case
6:return[6,q(a[1])];case
7:return[7,q(a[1])];case
8:var
c=a[1];return[8,c,q(a[2])];case
9:var
b=a[1];return[9,b,b,q(a[3])];case
10:return[10,q(a[1])];case
11:return[11,q(a[1])];case
12:return[12,q(a[1])];case
13:return[13,q(a[1])];default:return[14,q(a[1])]}}function
w(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,w(a[1],b)];case
1:return[1,w(a[1],b)];case
2:return[2,w(a[1],b)];case
3:return[3,w(a[1],b)];case
4:return[4,w(a[1],b)];case
5:return[5,w(a[1],b)];case
6:return[6,w(a[1],b)];case
7:return[7,w(a[1],b)];case
8:var
c=a[1];return[8,c,w(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,w(a[3],b)];case
10:return[10,w(a[1],b)];case
11:return[11,w(a[1],b)];case
12:return[12,w(a[1],b)];case
13:return[13,w(a[1],b)];default:return[14,w(a[1],b)]}}function
p(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,p(a[1],b)];case
1:return[1,p(a[1],b)];case
2:var
c=a[1];return[2,c,p(a[2],b)];case
3:var
d=a[1];return[3,d,p(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,p(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,p(a[4],b)];case
6:var
k=a[3],l=a[2],m=a[1];return[6,m,l,k,p(a[4],b)];case
7:var
n=a[3],o=a[2],q=a[1];return[7,q,o,n,p(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,p(a[4],b)];case
9:return[9,p(a[1],b)];case
10:return[10,p(a[1],b)];case
11:var
u=a[1];return[11,u,p(a[2],b)];case
12:var
v=a[1];return[12,v,p(a[2],b)];case
13:var
w=a[2],x=a[1];return[13,x,w,p(a[3],b)];case
14:var
y=a[2],z=a[1];return[14,z,y,p(a[3],b)];case
15:return[15,p(a[1],b)];case
16:return[16,p(a[1],b)];case
17:var
A=a[1];return[17,A,p(a[2],b)];case
18:var
B=a[1];return[18,B,p(a[2],b)];case
19:return[19,p(a[1],b)];case
20:var
C=a[2],D=a[1];return[20,D,C,p(a[3],b)];case
21:var
E=a[1];return[21,E,p(a[2],b)];case
22:return[22,p(a[1],b)];case
23:var
F=a[1];return[23,F,p(a[2],b)];default:var
G=a[2],H=a[1];return[24,H,G,p(a[3],b)]}}function
ag(a){throw[0,aO,a]}aK([b,bL,0]);function
ah(a){return 0<=a?a:-a|0}function
aQ(a,b){var
c=g(a),e=g(b),d=v(c+e|0);D(a,0,d,0,c);D(b,0,d,c,e);return d}dI(0);bD(1);bD(2);function
aR(a,b){var
c=b;for(;;){if(c){var
d=c[2];j(a,c[1]);var
c=d;continue}return 0}}function
U(a,b){var
c=v(a);dr(c,0,a,b);return c}function
aS(a,b,c){if(0<=b)if(0<=c)if(!((g(a)-c|0)<b)){var
d=v(c);D(a,b,d,0,c);return d}return ag(bV)}function
aT(a,b,c,d,e){if(0<=e)if(0<=b)if(!((g(a)-e|0)<b))if(0<=d)if(!((g(c)-e|0)<d))return D(a,b,c,d,e);return ag(bW)}function
E(a,b,c,d,e){if(0<=e)if(0<=b)if(!((g(a)-e|0)<b))if(0<=d)if(!((g(c)-e|0)<d))return D(a,b,c,d,e);return ag(bX)}function
aU(a,b){return U(a,b)}function
as(d,b){if(b){var
a=b[1],h=[0,0],f=[0,0],i=b[2];aR(function(a){h[1]++;f[1]=f[1]+g(a)|0;return 0},b);var
e=v(f[1]+bE(g(d),h[1]-1|0)|0);D(a,0,e,0,g(a));var
c=[0,g(a)];aR(function(a){D(d,0,e,c[1],g(d));c[1]=c[1]+g(d)|0;D(a,0,e,c[1],g(a));c[1]=c[1]+g(a)|0;return 0},i);return e}return bY}var
aV=dP(0),V=bE(aV/8|0,(1<<(aV+bf|0))-1|0)-1|0;aK([b,bZ,0]);function
aW(a,b){var
c=[0,a[3]];for(;;){if(c[1]<(a[2]+b|0)){c[1]=2*c[1]|0;continue}if(V<c[1]){if(!((a[2]+b|0)<=V))throw[0,aP,b0];c[1]=V}var
d=v(c[1]);aT(a[1],0,d,0,a[2]);a[1]=d;a[3]=c[1];return 0}}function
W(a,b){var
c=g(b),d=a[2]+c|0;if(a[3]<d)aW(a,c);E(b,0,a[1],a[2],c);a[2]=d;return 0}var
at=6;function
aX(a){return[0,0,v(a)]}function
aY(a,b){var
c=g(a[2]),d=a[1]+b|0,e=c<d?1:0;if(e){var
f=c*2|0,j=du(f,d)?f:d,h=v(j);aT(a[2],0,h,0,c);a[2]=h;var
i=0}else
var
i=e;return i}function
X(a,b){aY(a,1);ae(a[2],a[1],b);a[1]=a[1]+1|0;return 0}function
e(a,b){var
c=g(b);aY(a,c);E(b,0,a[2],a[1],c);a[1]=a[1]+c|0;return 0}function
aZ(a){return aS(a[2],0,a[1])}function
au(a,b){var
c=b;for(;;)if(typeof
c==="number")return 0;else
switch(c[0]){case
0:var
d=c[1];e(a,b9);var
c=d;continue;case
1:var
f=c[1];e(a,b_);var
c=f;continue;case
2:var
g=c[1];e(a,b$);var
c=g;continue;case
3:var
h=c[1];e(a,ca);var
c=h;continue;case
4:var
i=c[1];e(a,cb);var
c=i;continue;case
5:var
j=c[1];e(a,cc);var
c=j;continue;case
6:var
k=c[1];e(a,cd);var
c=k;continue;case
7:var
l=c[1];e(a,ce);var
c=l;continue;case
8:var
m=c[2],n=c[1];e(a,cf);au(a,n);e(a,cg);var
c=m;continue;case
9:var
o=c[3],p=c[1];e(a,ch);au(a,p);e(a,ci);var
c=o;continue;case
10:var
q=c[1];e(a,cj);var
c=q;continue;case
11:var
r=c[1];e(a,ck);var
c=r;continue;case
12:var
s=c[1];e(a,cl);var
c=s;continue;case
13:var
t=c[1];e(a,cm);var
c=t;continue;default:var
u=c[1];e(a,cn);var
c=u;continue}}function
t(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,t(a[1])];case
1:return[1,t(a[1])];case
2:return[2,t(a[1])];case
3:return[3,t(a[1])];case
4:return[4,t(a[1])];case
5:return[5,t(a[1])];case
6:return[6,t(a[1])];case
7:return[7,t(a[1])];case
8:var
b=a[1];return[8,b,t(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,t(a[3])];case
10:return[10,t(a[1])];case
11:return[11,t(a[1])];case
12:return[12,t(a[1])];case
13:return[13,t(a[1])];default:return[14,t(a[1])]}}function
i(a){if(typeof
a==="number"){var
v=function(a){return 0},w=function(a){return 0},x=function(a){return 0};return[0,function(a){return 0},x,w,v]}else
switch(a[0]){case
0:var
b=i(a[1]),y=b[4],z=b[3],A=b[2],B=b[1],C=function(a){j(A,0);return 0};return[0,function(a){j(B,0);return 0},C,z,y];case
1:var
c=i(a[1]),D=c[4],E=c[3],F=c[2],G=c[1],H=function(a){j(F,0);return 0};return[0,function(a){j(G,0);return 0},H,E,D];case
2:var
d=i(a[1]),I=d[4],J=d[3],K=d[2],L=d[1],M=function(a){j(K,0);return 0};return[0,function(a){j(L,0);return 0},M,J,I];case
3:var
e=i(a[1]),N=e[4],O=e[3],P=e[2],Q=e[1],R=function(a){j(P,0);return 0};return[0,function(a){j(Q,0);return 0},R,O,N];case
4:var
f=i(a[1]),S=f[4],T=f[3],U=f[2],V=f[1],W=function(a){j(U,0);return 0};return[0,function(a){j(V,0);return 0},W,T,S];case
5:var
g=i(a[1]),X=g[4],Y=g[3],Z=g[2],_=g[1],$=function(a){j(Z,0);return 0};return[0,function(a){j(_,0);return 0},$,Y,X];case
6:var
k=i(a[1]),aa=k[4],ab=k[3],ac=k[2],ad=k[1],ae=function(a){j(ac,0);return 0};return[0,function(a){j(ad,0);return 0},ae,ab,aa];case
7:var
l=i(a[1]),af=l[4],ag=l[3],ah=l[2],ai=l[1],aj=function(a){j(ah,0);return 0};return[0,function(a){j(ai,0);return 0},aj,ag,af];case
8:var
m=i(a[2]),ak=m[4],al=m[3],am=m[2],an=m[1],ao=function(a){j(am,0);return 0};return[0,function(a){j(an,0);return 0},ao,al,ak];case
9:var
ap=a[2],aq=a[1],n=i(a[3]),ar=n[4],as=n[3],at=n[2],au=n[1],o=i(h(t(aq),ap)),av=o[4],aw=o[3],ax=o[2],ay=o[1],az=function(a){j(av,0);j(ar,0);return 0},aA=function(a){j(as,0);j(aw,0);return 0},aB=function(a){j(ax,0);j(at,0);return 0};return[0,function(a){j(au,0);j(ay,0);return 0},aB,aA,az];case
10:var
p=i(a[1]),aC=p[4],aD=p[3],aE=p[2],aF=p[1],aG=function(a){j(aE,0);return 0};return[0,function(a){j(aF,0);return 0},aG,aD,aC];case
11:var
q=i(a[1]),aH=q[4],aI=q[3],aJ=q[2],aK=q[1],aL=function(a){j(aJ,0);return 0};return[0,function(a){j(aK,0);return 0},aL,aI,aH];case
12:var
r=i(a[1]),aM=r[4],aN=r[3],aO=r[2],aP=r[1],aQ=function(a){j(aO,0);return 0};return[0,function(a){j(aP,0);return 0},aQ,aN,aM];case
13:var
s=i(a[1]),aR=s[4],aS=s[3],aT=s[2],aU=s[1],aV=function(a){j(aR,0);return 0},aW=function(a){j(aS,0);return 0},aX=function(a){j(aT,0);return 0};return[0,function(a){j(aU,0);return 0},aX,aW,aV];default:var
u=i(a[1]),aY=u[4],aZ=u[3],a0=u[2],a1=u[1],a2=function(a){j(aY,0);return 0},a3=function(a){j(aZ,0);return 0},a4=function(a){j(a0,0);return 0};return[0,function(a){j(a1,0);return 0},a4,a3,a2]}}function
h(a,b){if(typeof
a==="number")if(typeof
b==="number")return 0;else
switch(b[0]){case
10:var
c=0;break;case
11:var
c=1;break;case
12:var
c=2;break;case
13:var
c=3;break;case
14:var
c=4;break;case
8:var
c=5;break;case
9:var
c=6;break;default:throw[0,s,co]}else
switch(a[0]){case
0:var
x=a[1];if(typeof
b==="number")var
d=1;else
switch(b[0]){case
0:return[0,h(x,b[1])];case
8:var
c=5,d=0;break;case
9:var
c=6,d=0;break;case
10:var
c=0,d=0;break;case
11:var
c=1,d=0;break;case
12:var
c=2,d=0;break;case
13:var
c=3,d=0;break;case
14:var
c=4,d=0;break;default:var
d=1}if(d)var
c=7;break;case
1:var
y=a[1];if(typeof
b==="number")var
e=1;else
switch(b[0]){case
1:return[1,h(y,b[1])];case
8:var
c=5,e=0;break;case
9:var
c=6,e=0;break;case
10:var
c=0,e=0;break;case
11:var
c=1,e=0;break;case
12:var
c=2,e=0;break;case
13:var
c=3,e=0;break;case
14:var
c=4,e=0;break;default:var
e=1}if(e)var
c=7;break;case
2:var
z=a[1];if(typeof
b==="number")var
f=1;else
switch(b[0]){case
2:return[2,h(z,b[1])];case
8:var
c=5,f=0;break;case
9:var
c=6,f=0;break;case
10:var
c=0,f=0;break;case
11:var
c=1,f=0;break;case
12:var
c=2,f=0;break;case
13:var
c=3,f=0;break;case
14:var
c=4,f=0;break;default:var
f=1}if(f)var
c=7;break;case
3:var
A=a[1];if(typeof
b==="number")var
g=1;else
switch(b[0]){case
3:return[3,h(A,b[1])];case
8:var
c=5,g=0;break;case
9:var
c=6,g=0;break;case
10:var
c=0,g=0;break;case
11:var
c=1,g=0;break;case
12:var
c=2,g=0;break;case
13:var
c=3,g=0;break;case
14:var
c=4,g=0;break;default:var
g=1}if(g)var
c=7;break;case
4:var
B=a[1];if(typeof
b==="number")var
k=1;else
switch(b[0]){case
4:return[4,h(B,b[1])];case
8:var
c=5,k=0;break;case
9:var
c=6,k=0;break;case
10:var
c=0,k=0;break;case
11:var
c=1,k=0;break;case
12:var
c=2,k=0;break;case
13:var
c=3,k=0;break;case
14:var
c=4,k=0;break;default:var
k=1}if(k)var
c=7;break;case
5:var
C=a[1];if(typeof
b==="number")var
l=1;else
switch(b[0]){case
5:return[5,h(C,b[1])];case
8:var
c=5,l=0;break;case
9:var
c=6,l=0;break;case
10:var
c=0,l=0;break;case
11:var
c=1,l=0;break;case
12:var
c=2,l=0;break;case
13:var
c=3,l=0;break;case
14:var
c=4,l=0;break;default:var
l=1}if(l)var
c=7;break;case
6:var
D=a[1];if(typeof
b==="number")var
m=1;else
switch(b[0]){case
6:return[6,h(D,b[1])];case
8:var
c=5,m=0;break;case
9:var
c=6,m=0;break;case
10:var
c=0,m=0;break;case
11:var
c=1,m=0;break;case
12:var
c=2,m=0;break;case
13:var
c=3,m=0;break;case
14:var
c=4,m=0;break;default:var
m=1}if(m)var
c=7;break;case
7:var
E=a[1];if(typeof
b==="number")var
n=1;else
switch(b[0]){case
7:return[7,h(E,b[1])];case
8:var
c=5,n=0;break;case
9:var
c=6,n=0;break;case
10:var
c=0,n=0;break;case
11:var
c=1,n=0;break;case
12:var
c=2,n=0;break;case
13:var
c=3,n=0;break;case
14:var
c=4,n=0;break;default:var
n=1}if(n)var
c=7;break;case
8:var
F=a[2],G=a[1];if(typeof
b==="number")var
p=1;else
switch(b[0]){case
8:var
H=b[1],I=h(F,b[2]);return[8,h(G,H),I];case
10:var
c=0,p=0;break;case
11:var
c=1,p=0;break;case
12:var
c=2,p=0;break;case
13:var
c=3,p=0;break;case
14:var
c=4,p=0;break;default:var
p=1}if(p)throw[0,s,cx];break;case
9:var
J=a[3],K=a[2],L=a[1];if(typeof
b==="number")var
o=1;else
switch(b[0]){case
8:var
c=5,o=0;break;case
9:var
M=b[3],N=b[2],O=b[1],w=i(h(t(K),O)),P=w[4];j(w[2],0);j(P,0);return[9,L,N,h(J,M)];case
10:var
c=0,o=0;break;case
11:var
c=1,o=0;break;case
12:var
c=2,o=0;break;case
13:var
c=3,o=0;break;case
14:var
c=4,o=0;break;default:var
o=1}if(o)throw[0,s,cy];break;case
10:var
Q=a[1];if(typeof
b!=="number"&&10===b[0])return[10,h(Q,b[1])];throw[0,s,cz];case
11:var
R=a[1];if(typeof
b==="number")var
v=1;else
switch(b[0]){case
10:var
c=0,v=0;break;case
11:return[11,h(R,b[1])];default:var
v=1}if(v)throw[0,s,cA];break;case
12:var
S=a[1];if(typeof
b==="number")var
u=1;else
switch(b[0]){case
10:var
c=0,u=0;break;case
11:var
c=1,u=0;break;case
12:return[12,h(S,b[1])];default:var
u=1}if(u)throw[0,s,cB];break;case
13:var
T=a[1];if(typeof
b==="number")var
r=1;else
switch(b[0]){case
10:var
c=0,r=0;break;case
11:var
c=1,r=0;break;case
12:var
c=2,r=0;break;case
13:return[13,h(T,b[1])];default:var
r=1}if(r)throw[0,s,cC];break;default:var
U=a[1];if(typeof
b==="number")var
q=1;else
switch(b[0]){case
10:var
c=0,q=0;break;case
11:var
c=1,q=0;break;case
12:var
c=2,q=0;break;case
13:var
c=3,q=0;break;case
14:return[14,h(U,b[1])];default:var
q=1}if(q)throw[0,s,cD]}switch(c){case
0:throw[0,s,cr];case
1:throw[0,s,cs];case
2:throw[0,s,ct];case
3:throw[0,s,cu];case
4:throw[0,s,cv];case
5:throw[0,s,cp];case
6:throw[0,s,cq];default:throw[0,s,cw]}}var
u=aK([b,cE,0]);function
av(a,b){if(typeof
a==="number")return[0,0,b];else{if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw u}}function
Y(a,b,c){var
d=av(a,c);if(typeof
b==="number"){if(0===b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw u}return[0,d[1],[0,b[1]],d[2]]}function
dn(a,b,c){if(typeof
b==="number")return[0,0,c];else
switch(b[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
y=o(b[1],c[1]);return[0,[0,y[1]],y[2]]}break;case
1:if(typeof
c!=="number"&&0===c[0]){var
z=o(b[1],c[1]);return[0,[1,z[1]],z[2]]}break;case
2:var
ah=b[2],A=av(b[1],c),g=A[2],ai=A[1];if(typeof
g!=="number"&&1===g[0]){var
B=o(ah,g[1]);return[0,[2,ai,B[1]],B[2]]}throw u;case
3:var
aj=b[2],C=av(b[1],c),h=C[2],ak=C[1];if(typeof
h!=="number"&&1===h[0]){var
D=o(aj,h[1]);return[0,[3,ak,D[1]],D[2]]}throw u;case
4:var
al=b[4],am=b[1],i=Y(b[2],b[3],c),j=i[3],an=i[2],ao=i[1];if(typeof
j!=="number"&&2===j[0]){var
E=o(al,j[1]);return[0,[4,am,ao,an,E[1]],E[2]]}throw u;case
5:var
ap=b[4],aq=b[1],l=Y(b[2],b[3],c),m=l[3],ar=l[2],as=l[1];if(typeof
m!=="number"&&3===m[0]){var
F=o(ap,m[1]);return[0,[5,aq,as,ar,F[1]],F[2]]}throw u;case
6:var
at=b[4],au=b[1],n=Y(b[2],b[3],c),p=n[3],aw=n[2],ax=n[1];if(typeof
p!=="number"&&4===p[0]){var
G=o(at,p[1]);return[0,[6,au,ax,aw,G[1]],G[2]]}throw u;case
7:var
ay=b[4],az=b[1],r=Y(b[2],b[3],c),s=r[3],aA=r[2],aB=r[1];if(typeof
s!=="number"&&5===s[0]){var
H=o(ay,s[1]);return[0,[7,az,aB,aA,H[1]],H[2]]}throw u;case
8:var
aC=b[4],aD=b[1],t=Y(b[2],b[3],c),v=t[3],aE=t[2],aF=t[1];if(typeof
v!=="number"&&6===v[0]){var
I=o(aC,v[1]);return[0,[8,aD,aF,aE,I[1]],I[2]]}throw u;case
9:if(typeof
c!=="number"&&7===c[0]){var
J=o(b[1],c[1]);return[0,[9,J[1]],J[2]]}break;case
10:var
K=o(b[1],c);return[0,[10,K[1]],K[2]];case
11:var
aG=b[1],L=o(b[2],c);return[0,[11,aG,L[1]],L[2]];case
12:var
aH=b[1],M=o(b[2],c);return[0,[12,aH,M[1]],M[2]];case
13:if(typeof
c!=="number"&&8===c[0]){var
N=c[1],aI=c[2],aJ=b[3],aK=b[1];if(ad([0,b[2]],[0,N]))throw u;var
O=o(aJ,aI);return[0,[13,aK,N,O[1]],O[2]]}break;case
14:if(typeof
c!=="number"&&9===c[0]){var
P=c[1],aL=c[3],aM=b[3],aN=b[2],aO=b[1],aP=[0,q(P)];if(ad([0,q(aN)],aP))throw u;var
Q=o(aM,q(aL));return[0,[14,aO,P,Q[1]],Q[2]]}break;case
15:if(typeof
c!=="number"&&10===c[0]){var
R=o(b[1],c[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
c!=="number"&&11===c[0]){var
S=o(b[1],c[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aQ=b[1],T=o(b[2],c);return[0,[17,aQ,T[1]],T[2]];case
18:var
U=b[2],w=b[1];if(0===w[0]){var
Z=w[1],aU=Z[2],_=o(Z[1],c),aV=_[1],$=o(U,_[2]);return[0,[18,[0,[0,aV,aU]],$[1]],$[2]]}var
aa=w[1],aW=aa[2],ab=o(aa[1],c),aX=ab[1],ac=o(U,ab[2]);return[0,[18,[1,[0,aX,aW]],ac[1]],ac[2]];case
19:if(typeof
c!=="number"&&13===c[0]){var
V=o(b[1],c[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
c!=="number"&&1===c[0]){var
aR=b[2],aS=b[1],W=o(b[3],c[1]);return[0,[20,aS,aR,W[1]],W[2]]}break;case
21:if(typeof
c!=="number"&&2===c[0]){var
aT=b[1],X=o(b[2],c[1]);return[0,[21,aT,X[1]],X[2]]}break;case
23:var
e=b[2],d=b[1];if(typeof
d==="number")switch(d){case
0:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
1:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
2:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
3:if(typeof
c!=="number"&&14===c[0]){var
ae=o(e,c[1]);return[0,[23,3,ae[1]],ae[2]]}throw u;default:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c])}else
switch(d[0]){case
0:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
1:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
2:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
3:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
4:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
5:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
6:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
7:return a<50?f(1+a,[7,d[1],d[2]],e,c):k(f,[0,[7,d[1],d[2]],e,c]);case
8:var
aY=d[1],af=x(d[2],e,c),ag=af[2];return[0,[23,[8,aY,af[1]],ag[1]],ag[2]];case
9:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);default:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c])}}throw u}function
f(a,b,c,d){var
e=o(c,d);return[0,[23,b,e[1]],e[2]]}function
o(b,c){return O(dn(0,b,c))}function
dY(b,c,d){return O(f(0,b,c,d))}function
x(a,b,c){if(typeof
a==="number")return[0,0,o(b,c)];else
switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=x(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
g=x(a[1],b,c[1]);return[0,[1,g[1]],g[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
k=x(a[1],b,c[1]);return[0,[2,k[1]],k[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
l=x(a[1],b,c[1]);return[0,[3,l[1]],l[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
m=x(a[1],b,c[1]);return[0,[4,m[1]],m[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
n=x(a[1],b,c[1]);return[0,[5,n[1]],n[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
p=x(a[1],b,c[1]);return[0,[6,p[1]],p[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
r=x(a[1],b,c[1]);return[0,[7,r[1]],r[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
s=c[1],D=c[2],E=a[2];if(ad([0,a[1]],[0,s]))throw u;var
v=x(E,b,D);return[0,[8,s,v[1]],v[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],F=c[3],G=a[3],H=a[2],I=a[1],J=[0,q(e)];if(ad([0,q(I)],J))throw u;var
K=[0,q(d)];if(ad([0,q(H)],K))throw u;var
w=i(h(t(e),d)),L=w[4];j(w[2],0);j(L,0);var
y=x(q(G),b,F),M=y[2];return[0,[9,e,d,t(y[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
z=x(a[1],b,c[1]);return[0,[10,z[1]],z[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
A=x(a[1],b,c[1]);return[0,[11,A[1]],A[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
B=x(a[1],b,c[1]);return[0,[13,B[1]],B[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
C=x(a[1],b,c[1]);return[0,[14,C[1]],C[2]]}break}throw u}function
y(a,b,c){var
d=g(c),l=0<=b?a:0,f=ah(b);if(f<=d)return c;var
m=2===l?48:32,e=U(f,m);switch(l){case
0:E(c,0,e,0,d);break;case
1:E(c,0,e,f-d|0,d);break;default:if(0<d){if(43===B(c,0))var
h=1;else
if(45===B(c,0))var
h=1;else
if(32===B(c,0))var
h=1;else
var
j=0,h=0;if(h){ae(e,0,B(c,0));E(c,1,e,(f-d|0)+1|0,d-1|0);var
j=1}}else
var
j=0;if(!j){if(1<d)if(48===B(c,0)){if(bt===B(c,1))var
k=1;else
if(88===B(c,1))var
k=1;else
var
i=0,k=0;if(k){ae(e,1,B(c,1));E(c,2,e,(f-d|0)+2|0,d-2|0);var
i=1}}else
var
i=0;else
var
i=0;if(!i)E(c,0,e,f-d|0,d)}}return e}function
Q(a,b){var
d=ah(a),c=g(b),e=B(b,0);if(58<=e)var
f=71<=e?5<(e-97|0)>>>0?1:0:65<=e?0:1;else{if(32===e)var
h=1;else
if(43<=e)switch(e-43|0){case
5:if(c<(d+2|0))if(1<c){var
l=bt===B(b,1)?0:88===B(b,1)?0:1;if(!l){var
j=U(d+2|0,48);ae(j,1,B(b,1));E(b,2,j,(d-c|0)+4|0,c-2|0);return j}}var
f=0,h=0;break;case
0:case
2:var
h=1;break;case
1:case
3:case
4:var
f=1,h=0;break;default:var
f=0,h=0}else
var
f=1,h=0;if(h){if(c<(d+1|0)){var
i=U(d+1|0,48);ae(i,0,e);E(b,1,i,(d-c|0)+2|0,c-1|0);return i}var
f=1}}if(!f)if(c<d){var
k=U(d,48);E(b,0,k,d-c|0,c);return k}return b}function
a0(a){var
l=0;for(;;){if(g(a)<=l)var
n=0;else{var
f=ar(a,l),A=14<=f?34===f?1:92===f?1:0:11<=f?13<=f?1:0:8<=f?1:0;if(A)var
n=1;else{if(am(f)){var
l=l+1|0;continue}var
n=1}}if(n){var
b=[0,0],s=g(a)-1|0,u=0;if(!(s<0)){var
k=u;for(;;){var
e=ar(a,k),B=14<=e?34===e?1:92===e?1:0:11<=e?13<=e?1:0:8<=e?1:0,y=B?2:am(e)?1:4;b[1]=b[1]+y|0;var
z=k+1|0;if(s!==k){var
k=z;continue}break}}if(b[1]===g(a)){var
p=g(a),q=v(p);D(a,0,q,0,p);var
o=q}else{var
c=v(b[1]);b[1]=0;var
t=g(a)-1|0,w=0;if(!(t<0)){var
i=w;for(;;){var
d=ar(a,i),j=d-34|0;if(58<j>>>0)if(-20<=j)var
m=1;else{switch(j+34|0){case
8:r(c,b[1],92);b[1]++;r(c,b[1],98);var
h=1;break;case
9:r(c,b[1],92);b[1]++;r(c,b[1],116);var
h=1;break;case
10:r(c,b[1],92);b[1]++;r(c,b[1],bk);var
h=1;break;case
13:r(c,b[1],92);b[1]++;r(c,b[1],114);var
h=1;break;default:var
m=1,h=0}if(h)var
m=0}else
var
m=56<(j-1|0)>>>0?(r(c,b[1],92),b[1]++,r(c,b[1],d),0):1;if(m)if(am(d))r(c,b[1],d);else{r(c,b[1],92);b[1]++;r(c,b[1],48+(d/bc|0)|0);b[1]++;r(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;r(c,b[1],48+(d%10|0)|0)}b[1]++;var
x=i+1|0;if(t!==i){var
i=x;continue}break}}var
o=c}}else
var
o=a;return as(o,cF)}}function
aw(a,b){switch(a){case
0:var
c=cT;break;case
1:var
c=cU;break;case
2:var
c=cV;break;case
3:var
c=cW;break;case
4:var
c=cX;break;case
5:var
c=cY;break;case
6:var
c=cZ;break;case
7:var
c=c0;break;case
8:var
c=c1;break;case
9:var
c=c2;break;case
10:var
c=c3;break;case
11:var
c=c4;break;default:var
c=c5}return as(aU(1,b),c)}function
a1(a,b){switch(a){case
0:var
c=cG;break;case
1:var
c=cH;break;case
2:var
c=cI;break;case
3:var
c=cJ;break;case
4:var
c=cK;break;case
5:var
c=cL;break;case
6:var
c=cM;break;case
7:var
c=cN;break;case
8:var
c=cO;break;case
9:var
c=cP;break;case
10:var
c=cQ;break;case
11:var
c=cR;break;default:var
c=cS}return al(c,b)}function
a2(a,b){return al(aw(a,108),b)}function
a3(a,b){return al(aw(a,bk),b)}function
a4(a,b){return dw(aw(a,76),b)}function
J(a,b,c){var
q=ah(b);if(15===a)var
l=c6;else{var
p=ah(q);switch(a){case
15:var
h=70;break;case
0:case
1:case
2:var
h=102;break;case
3:case
4:case
5:var
h=101;break;case
6:case
7:case
8:var
h=69;break;case
9:case
10:case
11:var
h=103;break;default:var
h=71}var
f=aX(16);X(f,37);switch(a){case
1:case
4:case
7:case
10:case
13:X(f,43);break;case
2:case
5:case
8:case
11:case
14:X(f,32);break}X(f,46);e(f,d(n+p));X(f,h);var
l=aZ(f)}var
i=ds(l,c);if(15===a){var
m=dp(c),r=g(i);if(3===m)return c<0?c7:c8;if(4<=m)return c9;var
j=0;for(;;){if(j===r)var
o=0;else{var
k=B(i,j)-46|0,s=23<k>>>0?55===k?1:0:21<(k-1|0)>>>0?1:0;if(!s){var
j=j+1|0;continue}var
o=1}return o?i:aQ(i,c_)}}return i}function
_(a,b,i,d,e){var
h=b,f=d,g=e;for(;;)if(typeof
g==="number")return C(h,i,f);else
switch(g[0]){case
0:var
Q=g[1];return function(a){return l(h,i,[5,f,a],Q)};case
1:var
R=g[1];return function(a){if(39===a)var
b=bP;else
if(92===a)var
b=bQ;else{if(14<=a)var
c=0;else
switch(a){case
8:var
b=bR,c=1;break;case
9:var
b=bS,c=1;break;case
10:var
b=bT,c=1;break;case
13:var
b=bU,c=1;break;default:var
c=0}if(!c)if(am(a)){var
e=v(1);r(e,0,a);var
b=e}else{var
d=v(4);r(d,0,92);r(d,1,48+(a/bc|0)|0);r(d,2,48+((a/10|0)%10|0)|0);r(d,3,48+(a%10|0)|0);var
b=d}}return l(h,i,[4,f,as(b,c$)],R)};case
2:var
L=g[2],M=g[1];return a<50?Z(1+a,h,i,f,L,M,function(a){return a}):k(Z,[0,h,i,f,L,M,function(a){return a}]);case
3:return a<50?Z(1+a,h,i,f,g[2],g[1],a0):k(Z,[0,h,i,f,g[2],g[1],a0]);case
4:return a<50?K(1+a,h,i,f,g[4],g[2],g[3],a1,g[1]):k(K,[0,h,i,f,g[4],g[2],g[3],a1,g[1]]);case
5:return a<50?K(1+a,h,i,f,g[4],g[2],g[3],a2,g[1]):k(K,[0,h,i,f,g[4],g[2],g[3],a2,g[1]]);case
6:return a<50?K(1+a,h,i,f,g[4],g[2],g[3],a3,g[1]):k(K,[0,h,i,f,g[4],g[2],g[3],a3,g[1]]);case
7:return a<50?K(1+a,h,i,f,g[4],g[2],g[3],a4,g[1]):k(K,[0,h,i,f,g[4],g[2],g[3],a4,g[1]]);case
8:var
w=g[4],x=g[3],A=g[2],z=g[1];if(typeof
A==="number"){if(typeof
x==="number")return 0===x?function(a){return l(h,i,[4,f,J(z,at,a)],w)}:function(a,b){return l(h,i,[4,f,J(z,a,b)],w)};var
ag=x[1];return function(a){return l(h,i,[4,f,J(z,ag,a)],w)}}else{if(0===A[0]){var
F=A[2],G=A[1];if(typeof
x==="number")return 0===x?function(a){return l(h,i,[4,f,y(G,F,J(z,at,a))],w)}:function(a,b){return l(h,i,[4,f,y(G,F,J(z,a,b))],w)};var
ah=x[1];return function(a){return l(h,i,[4,f,y(G,F,J(z,ah,a))],w)}}var
H=A[1];if(typeof
x==="number")return 0===x?function(a,b){return l(h,i,[4,f,y(H,a,J(z,at,b))],w)}:function(a,b,c){return l(h,i,[4,f,y(H,a,J(z,b,c))],w)};var
ai=x[1];return function(a,b){return l(h,i,[4,f,y(H,a,J(z,ai,b))],w)}}case
9:var
S=g[1];return function(a){var
b=a?bM:bN;return l(h,i,[4,f,b],S)};case
10:var
f=[7,f],g=g[1];continue;case
11:var
f=[2,f,g[1]],g=g[2];continue;case
12:var
f=[3,f,g[1]],g=g[2];continue;case
13:var
T=g[3],U=g[2],I=aX(16);au(I,U);var
P=aZ(I);return function(a){return l(h,i,[4,f,P],T)};case
14:var
V=g[3],W=g[2];return function(a){var
c=a[1],b=o(c,q(t(W)));if(typeof
b[2]==="number")return l(h,i,f,p(b[1],V));throw u};case
15:var
X=g[1];return function(c,b){return l(h,i,[6,f,function(a){return C(c,a,b)}],X)};case
16:var
Y=g[1];return function(a){return l(h,i,[6,f,a],Y)};case
17:var
f=[0,f,g[1]],g=g[2];continue;case
18:var
D=g[1];if(0===D[0]){var
c=g[2],_=D[1][1],$=0,h=function(f,h,c){return function(a,b){return l(h,a,[1,f,[0,b]],c)}}(f,h,c),f=$,g=_;continue}var
E=g[2],aa=D[1][1],ab=0,h=function(f,h,E){return function(a,b){return l(h,a,[1,f,[1,b]],E)}}(f,h,E),f=ab,g=aa;continue;case
19:throw[0,s,db];case
20:var
ac=g[3],ad=[8,f,dc];return function(a){return l(h,i,ad,ac)};case
21:var
ae=g[2];return function(a){return l(h,i,[4,f,al(dd,a)],ae)};case
22:var
af=g[1];return function(a){return l(h,i,[5,f,a],af)};case
23:var
n=g[2],B=g[1];if(typeof
B==="number")switch(B){case
0:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
1:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
2:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
3:throw[0,s,de];default:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n])}else
switch(B[0]){case
0:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
1:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
2:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
3:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
4:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
5:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
6:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
7:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
8:return a<50?ay(1+a,h,i,f,B[2],n):k(ay,[0,h,i,f,B[2],n]);case
9:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);default:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n])}default:var
N=g[3],O=g[1];return a<50?ax(1+a,h,i,f,N,O,j(g[2],0)):k(ax,[0,h,i,f,N,O,j(g[2],0)])}}function
ay(a,g,c,d,e,f){if(typeof
e==="number")return a<50?m(1+a,g,c,d,f):k(m,[0,g,c,d,f]);else
switch(e[0]){case
0:var
b=e[1];return function(a){return A(g,c,d,b,f)};case
1:var
i=e[1];return function(a){return A(g,c,d,i,f)};case
2:var
j=e[1];return function(a){return A(g,c,d,j,f)};case
3:var
l=e[1];return function(a){return A(g,c,d,l,f)};case
4:var
n=e[1];return function(a){return A(g,c,d,n,f)};case
5:var
o=e[1];return function(a){return A(g,c,d,o,f)};case
6:var
p=e[1];return function(a){return A(g,c,d,p,f)};case
7:var
q=e[1];return function(a){return A(g,c,d,q,f)};case
8:var
r=e[2];return function(a){return A(g,c,d,r,f)};case
9:var
u=e[3],v=e[2],x=h(t(e[1]),v);return function(a){return A(g,c,d,w(x,u),f)};case
10:var
y=e[1];return function(a,b){return A(g,c,d,y,f)};case
11:var
z=e[1];return function(a){return A(g,c,d,z,f)};case
12:var
B=e[1];return function(a){return A(g,c,d,B,f)};case
13:throw[0,s,df];default:throw[0,s,dg]}}function
m(a,b,c,d,e){return a<50?_(1+a,b,c,[8,d,a5],e):k(_,[0,b,c,[8,d,a5],e])}function
Z(a,h,c,d,e,f,g){if(typeof
f==="number")return function(a){return l(h,c,[4,d,j(g,a)],e)};else{if(0===f[0]){var
b=f[2],i=f[1];return function(a){return l(h,c,[4,d,y(i,b,j(g,a))],e)}}var
k=f[1];return function(a,b){return l(h,c,[4,d,y(k,a,j(g,b))],e)}}}function
K(a,k,j,d,e,f,g,h,i){if(typeof
f==="number"){if(typeof
g==="number")return 0===g?function(a){return l(k,j,[4,d,C(h,i,a)],e)}:function(a,b){return l(k,j,[4,d,Q(a,C(h,i,b))],e)};var
b=g[1];return function(a){return l(k,j,[4,d,Q(b,C(h,i,a))],e)}}else{if(0===f[0]){var
c=f[2],m=f[1];if(typeof
g==="number")return 0===g?function(a){return l(k,j,[4,d,y(m,c,C(h,i,a))],e)}:function(a,b){return l(k,j,[4,d,y(m,c,Q(a,C(h,i,b)))],e)};var
o=g[1];return function(a){return l(k,j,[4,d,y(m,c,Q(o,C(h,i,a)))],e)}}var
n=f[1];if(typeof
g==="number")return 0===g?function(a,b){return l(k,j,[4,d,y(n,a,C(h,i,b))],e)}:function(a,b,c){return l(k,j,[4,d,y(n,a,Q(b,C(h,i,c)))],e)};var
p=g[1];return function(a,b){return l(k,j,[4,d,y(n,a,Q(p,C(h,i,b)))],e)}}}function
ax(a,b,c,d,e,f,g){if(f){var
h=f[1];return function(a){return da(b,c,d,e,h,j(g,a))}}return a<50?_(1+a,b,c,[4,d,g],e):k(_,[0,b,c,[4,d,g],e])}function
l(b,i,d,e){return O(_(0,b,i,d,e))}function
A(g,c,d,e,f){return O(ay(0,g,c,d,e,f))}function
dZ(b,c,d,e){return O(m(0,b,c,d,e))}function
d0(h,c,d,e,f,g){return O(Z(0,h,c,d,e,f,g))}function
d1(k,j,d,e,f,g,h,i){return O(K(0,k,j,d,e,f,g,h,i))}function
da(b,c,d,e,f,g){return O(ax(0,b,c,d,e,f,g))}function
L(a,b){var
c=b;for(;;)if(typeof
c==="number")return 0;else
switch(c[0]){case
0:var
e=c[2],i=c[1];if(typeof
e==="number")switch(e){case
0:var
d=b1;break;case
1:var
d=b2;break;case
2:var
d=b3;break;case
3:var
d=b4;break;case
4:var
d=b5;break;case
5:var
d=b6;break;default:var
d=b7}else
switch(e[0]){case
0:var
d=e[1];break;case
1:var
d=e[1];break;default:var
d=aQ(b8,aU(1,e[1]))}L(a,i);return W(a,d);case
1:var
g=c[2],h=c[1];if(0===g[0]){var
k=g[1];L(a,h);W(a,dh);var
c=k;continue}var
l=g[1];L(a,h);W(a,di);var
c=l;continue;case
6:var
o=c[2];L(a,c[1]);return W(a,j(o,0));case
7:var
c=c[1];continue;case
8:var
p=c[2];L(a,c[1]);return ag(p);case
2:case
4:var
m=c[2];L(a,c[1]);return W(a,m);default:var
n=c[2];L(a,c[1]);var
f=a[2];if(a[3]<=f)aW(a,1);r(a[1],f,n);a[2]=f+1|0;return 0}}var
dl=adder(6,7),dk=addTextToDom,dj=dm[1];dk(j(l(function(a,b){var
g=64,d=1<=64?g:1,e=V<d?V:d,f=v(e),c=[0,f,0,e,f];L(c,b);return aS(c[1],0,c[2])},0,0,dj),dl).toString());function
bO(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{dH(d)}catch(f){}var
b=c;continue}return 0}}bO(dJ(0));return}(function(){return this}()));
