// Generated by js_of_ocaml 2.6
(function(y){"use strict";var
P="Sys_error",$=224,_="Invalid_argument",m=1024,O=57343,Z=512,Y="End_of_file",X="Failure",N="Undefined_recursive_module",W="Stack_overflow",e=128,d="",u=" : file already exists",K=56320,L=240,M=2048,a=248,V="Not_found",I="Assert_failure",J="/",H="toString",T="Sys_blocked_io",U="fd ",G="Out_of_memory",S="Match_failure",R="Division_by_zero",Q=1e3;function
ak(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
aC(a){return ak(a,1,a.length-1)}function
aM(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
x(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=m,c-=m)f+=e.apply(null,ak(a,b,Math.min(c,m)));return f}function
ac(a){if(a.t==2)a.c+=aM(a.l-a.c.length,"\0");else
a.c=x(a.c,0,a.c.length);a.t=0}function
ae(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aR(a){for(var
l=d,f=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<e){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<e;g++);if(g-c>Z){f.substr(0,1);l+=f;f=d;l+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(h<<6);if(h<$){b=i-12416;if(b<e)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(i<<6);if(h<L){b=i-925824;if(b<M||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==e&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>65535)f+=String.fromCharCode(55232+(b>>10),K+(b&1023));else
f+=String.fromCharCode(b);if(f.length>m){f.substr(0,1);l+=f;f=d}}return l+f}function
aQ(a){switch(a.t){case
9:return a.c;default:ac(a);case
0:if(ae(a.c)){a.t=9;return a.c}a.t=8;case
8:return aR(a.c)}}function
h(a,b,c){this.t=a;this.c=b;this.l=c}h.prototype.toString=function(){return aQ(this)};function
n(a,b,c){return a[b.toString()].apply(a,aC(c))}function
aS(a){for(var
h=d,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<e){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<e;g++);if(g-f>Z){c.substr(0,1);h+=c;c=d;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<M){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(e|b&63)}else
if(b<55296||b>=O)c+=String.fromCharCode($|b>>12,e|b>>6&63,e|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<K||j>O)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(L|b>>18,e|b>>12&63,e|b>>6&63,e|b&63)}if(c.length>m){c.substr(0,1);h+=c;c=d}}return h+c}function
af(a){var
b=9;if(!ae(a))b=8,a=aS(a);return new
h(b,a,a.length)}function
aJ(a,b){throw[0,a,b]}function
c(a){return new
h(0,a,a.length)}function
ai(a,b){aJ(a,c(b))}var
f=[0];function
g(a){ai(f.Sys_error,a)}function
aD(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
ad(a){ai(f.Invalid_argument,a)}function
k(a){if(a<0)ad("String.create");return new
h(a?2:9,d,a)}var
aj=0;function
aV(){return new
Date().getTime()/Q}function
z(){return Math.floor(aV())}function
i(a){this.data=a;this.inode=aj++;var
b=z();this.atime=b;this.mtime=b;this.ctime=b}i.prototype={truncate:function(){this.data=k(0);this.modified()},modified:function(){var
a=z();this.atime=a;this.mtime=a}};function
w(a){return a.l}function
ah(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
aA=J;function
p(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=aA+a;var
e=a.split(J),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
j(){this.content={};this.inode=aj++;var
a=z();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
r=new
j();r.mk(d,new
j());function
v(a){var
b=r;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))ah(a.orig);b=b.get(a[c])}return b}function
aP(a){var
c=p(a),b=v(c);return b
instanceof
j?1:0}function
aN(a){return new
h(4,a,a.length)}function
ab(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aW(a){if(a.t!=4)ab(a);return a.c}function
aB(a,b){var
f=p(a),d=r;for(var
k=0;k<f.length-1;k++){var
e=f[k];if(!d.exists(e))d.mk(e,new
j());d=d.get(e);if(!(d
instanceof
j))g(f.orig+u)}var
e=f[f.length-1];if(d.exists(e))g(f.orig+u);if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,b);else
if(b
instanceof
h)d.mk(e,new
i(b));else
if(b
instanceof
Array)d.mk(e,new
i(aN(b)));else
if(b.toString)d.mk(e,new
i(c(b.toString())));else
ad("caml_fs_register");return 0}function
aO(a){var
b=r,d=p(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
o(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?w(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
aX(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=p(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(aO(a)){if(aP(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+u);var
i=f.fd_last_idx?f.fd_last_idx:0,e=v(j);if(d.truncate)e.truncate();return o(i+1,e,d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;aB(a,k(0));var
e=v(j);return o(i+1,e,d)}else
ah(a)}o(0,new
i(k(0)));o(1,new
i(k(0)));o(2,new
i(k(0)));function
aE(a){var
b=f.fds[a];if(b.flags.wronly)g(U+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
aa(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?x(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?x(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)ab(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aT(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=y.console;b&&b.error&&b.error(a)}function
aU(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=y.console;b&&b.log&&b.log(a)}var
q=new
Array();function
aL(a,b){var
h=c(b),d=w(h),g=w(a.file.data),f=a.offset;if(f+d>=g){var
e=k(f+d);aa(a.file.data,0,e,0,g);aa(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
ag(a){var
b;switch(a){case
1:b=aU;break;case
2:b=aT;break;default:b=aL}var
e=f.fds[a];if(e.flags.rdonly)g(U+a+" is readonly");var
c={file:e.file,offset:e.offset,fd:a,opened:true,buffer:d,output:b};q[c.fd]=c;return c}function
aF(){var
a=0;for(var
b
in
q)if(q[b].opened)a=[0,q[b],a];return a}function
aH(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:Q}function
b(a,b,c){f[a+1]=b;if(c)f[c]=b}var
aG={};function
az(a){if((a.t&6)!=0)ac(a);return a.c}function
aK(a,b){aG[az(a)]=b;return 0}var
aI=0;function
l(a){a[2]=aI++;return a}var
A=[a,c(V),-7];b(11,[a,c(N),-12],N);b(10,[a,c(I),-11],I);b(9,[a,c(T),-10],T);b(8,[a,c(W),-9],W);b(7,[a,c(S),-8],S);b(6,A,V);b(5,[a,c(R),-6],R);b(4,[a,c(Y),-5],Y);b(3,[a,c(_),-4],_);b(2,[a,c(X),-3],X);b(1,[a,c(P),-2],P);b(0,[a,c(G),-1],G);l([a,c("Pervasives.Exit"),0]);aE(0);ag(1);ag(2);l([a,c("Array.Bottom"),0]);l([a,c("Sys.Break"),0]);l([a,c("CamlinternalFormat.Type_mismatch"),0]);var
B=[0,0],ar=c(H),aq=c(H),ap=c("Js.Error"),at=c("getElementById"),au=c("Dom_html.Canvas_not_available"),ay=c("render"),ax=c("createElement");function
C(a){B[1]=[0,a,B[1]];return 0}var
s=y,D=null,ao=s.Array,E=l([a,ap,0]),t=[0,E,{}],an=undefined,am=aH(t)===a?t:t[1];aK(c("jsError"),am);C(function(a){return a[1]===E?[0,af(n(a[2],aq,[0]))]:0});C(function(a){return a
instanceof
ao?0:[0,af(n(a,ar,[0]))]});var
as=s.document;l([a,au,0]);s.HTMLElement===an;var
F=n(as,at,[0,"content"]),av=React,aw=ReactDOM;if(F==D)throw A;n(aw,ay,[0,function(a){return n(av,ax,[0,"h1",D])},F]);function
al(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{aD(d)}catch(f){}var
b=c;continue}return 0}}al(aF(0));return}(function(){return this}()));
