// Generated by js_of_ocaml 2.6
(function(Q){"use strict";var
z="Sys_error",I="Invalid_argument",m=1024,H="End_of_file",G="Failure",y="Undefined_recursive_module",F="Stack_overflow",j=128,d="",q=" : file already exists",a=248,E="Not_found",w="Assert_failure",x="/",C="Sys_blocked_io",D="fd ",v="Out_of_memory",B="Match_failure",A="Division_by_zero";function
_(a,b){throw[0,a,b]}function
ab(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
aj(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
t(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=m,c-=m)f+=e.apply(null,aj(a,b,Math.min(c,m)));return f}function
S(a){if(a.t==2)a.c+=ab(a.l-a.c.length,"\0");else
a.c=t(a.c,0,a.c.length);a.t=0}function
V(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
ag(a){for(var
l=d,e=d,h,g,i,b,c=0,k=a.length;c<k;c++){g=a.charCodeAt(c);if(g<j){for(var
f=c+1;f<k&&(g=a.charCodeAt(f))<j;f++);if(f-c>512){e.substr(0,1);l+=e;e=d;l+=a.slice(c,f)}else
e+=a.slice(c,f);if(f==k)break;c=f}b=1;if(++c<k&&((i=a.charCodeAt(c))&-64)==j){h=i+(g<<6);if(g<224){b=h-12416;if(b<j)b=1}else{b=2;if(++c<k&&((i=a.charCodeAt(c))&-64)==j){h=i+(h<<6);if(g<240){b=h-925824;if(b<2048||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((i=a.charCodeAt(c))&-64)==j&&g<245){b=i-63447168+(h<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;e+="\ufffd"}else
if(b>65535)e+=String.fromCharCode(55232+(b>>10),56320+(b&1023));else
e+=String.fromCharCode(b);if(e.length>m){e.substr(0,1);l+=e;e=d}}return l+e}function
af(a){switch(a.t){case
9:return a.c;default:S(a);case
0:if(V(a.c)){a.t=9;return a.c}a.t=8;case
8:return ag(a.c)}}function
i(a,b,c){this.t=a;this.c=b;this.l=c}i.prototype.toString=function(){return af(this)};function
c(a){return new
i(0,a,a.length)}function
O(a,b){_(a,c(b))}var
e=[0];function
f(a){O(e.Sys_error,a)}function
W(a){if(!a.opened)f("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
L(a){O(e.Invalid_argument,a)}function
k(a){if(a<0)L("String.create");return new
i(a?2:9,d,a)}var
P=0;function
ak(){return new
Date().getTime()/1e3}function
u(){return Math.floor(ak())}function
g(a){this.data=a;this.inode=P++;var
b=u();this.atime=b;this.mtime=b;this.ctime=b}g.prototype={truncate:function(){this.data=k(0);this.modified()},modified:function(){var
a=u();this.atime=a;this.mtime=a}};function
s(a){return a.l}function
N(a){a=a
instanceof
i?a.toString():a;f(a+": No such file or directory")}var
T=x;function
n(a){a=a
instanceof
i?a.toString():a;if(a.charCodeAt(0)!=47)a=T+a;var
e=a.split(x),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
h(){this.content={};this.inode=P++;var
a=u();this.atime=a;this.mtime=a;this.ctime=a}h.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
p=new
h();p.mk(d,new
h());function
r(a){var
b=p;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))N(a.orig);b=b.get(a[c])}return b}function
ae(a){var
c=n(a),b=r(c);return b
instanceof
h?1:0}function
ac(a){return new
i(4,a,a.length)}function
K(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
al(a){if(a.t!=4)K(a);return a.c}function
U(a,b){var
j=n(a),d=p;for(var
k=0;k<j.length-1;k++){var
e=j[k];if(!d.exists(e))d.mk(e,new
h());d=d.get(e);if(!(d
instanceof
h))f(j.orig+q)}var
e=j[j.length-1];if(d.exists(e))f(j.orig+q);if(b
instanceof
h)d.mk(e,b);else
if(b
instanceof
g)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,new
g(b));else
if(b
instanceof
Array)d.mk(e,new
g(ac(b)));else
if(b.toString)d.mk(e,new
g(c(b.toString())));else
L("caml_fs_register");return 0}function
ad(a){var
b=p,d=n(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
l(a,b,c){if(e.fds===undefined)e.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?s(b.data):0;d.flags=c;e.fds[a]=d;e.fd_last_idx=a;return a}function
am(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=n(a);if(d.rdonly&&d.wronly)f(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)f(h+" : flags Open_text and Open_binary are not compatible");if(ad(a)){if(ae(a))f(h+" : is a directory");if(d.create&&d.excl)f(h+q);var
i=e.fd_last_idx?e.fd_last_idx:0,g=r(j);if(d.truncate)g.truncate();return l(i+1,g,d)}else
if(d.create){var
i=e.fd_last_idx?e.fd_last_idx:0;U(a,k(0));var
g=r(j);return l(i+1,g,d)}else
N(a)}l(0,new
g(k(0)));l(1,new
g(k(0)));l(2,new
g(k(0)));function
X(a){var
b=e.fds[a];if(b.flags.wronly)f(D+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
J(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?t(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?t(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)K(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
ah(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=Q.console;b&&b.error&&b.error(a)}function
ai(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=Q.console;b&&b.log&&b.log(a)}var
o=new
Array();function
aa(a,b){var
h=c(b),d=s(h),g=s(a.file.data),f=a.offset;if(f+d>=g){var
e=k(f+d);J(a.file.data,0,e,0,g);J(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
M(a){var
b;switch(a){case
1:b=ai;break;case
2:b=ah;break;default:b=aa}var
g=e.fds[a];if(g.flags.rdonly)f(D+a+" is readonly");var
c={file:g.file,offset:g.offset,fd:a,opened:true,buffer:d,output:b};o[c.fd]=c;return c}function
Y(){var
a=0;for(var
b
in
o)if(o[b].opened)a=[0,o[b],a];return a}function
b(a,b,c){e[a+1]=b;if(c)e[c]=b}var
Z=0;function
$(a){a[2]=Z++;return a}b(11,[a,c(y),-12],y);b(10,[a,c(w),-11],w);b(9,[a,c(C),-10],C);b(8,[a,c(F),-9],F);b(7,[a,c(B),-8],B);b(6,[a,c(E),-7],E);b(5,[a,c(A),-6],A);b(4,[a,c(H),-5],H);b(3,[a,c(I),-4],I);b(2,[a,c(G),-3],G);b(1,[a,c(z),-2],z);b(0,[a,c(v),-1],v);$([a,c("Pervasives.Exit"),0]);X(0);M(1);M(2);function
R(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{W(d)}catch(f){}var
b=c;continue}return 0}}R(Y(0));return}(function(){return this}()));
